// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApkGgbPPbPH9hBvyvH7Byx46dY-jFubuU',
    appId: '1:288118897213:web:e27827ff43b4da545d0854',
    messagingSenderId: '288118897213',
    projectId: 'task-management-163e6',
    authDomain: 'task-management-163e6.firebaseapp.com',
    storageBucket: 'task-management-163e6.appspot.com',
    measurementId: 'G-5E5Y8N72RD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1cJj7Kdj01tSUKaZ_DV_iJHqQsYcuL2k',
    appId: '1:288118897213:android:7db5df3351f623ef5d0854',
    messagingSenderId: '288118897213',
    projectId: 'task-management-163e6',
    storageBucket: 'task-management-163e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5XsuAIX6_4kZhJzwWTShvix8frccZgio',
    appId: '1:288118897213:ios:7b7b6bbc2da70e1d5d0854',
    messagingSenderId: '288118897213',
    projectId: 'task-management-163e6',
    storageBucket: 'task-management-163e6.appspot.com',
    iosBundleId: 'com.example.taskMgmt',
  );
}
